/**
 * discord.js - Post to Discord via Webhook (FREE, easiest setup)
 * 
 * SETUP:
 * 1. Open Discord, go to your server
 * 2. Right-click a channel → Edit Channel → Integrations → Webhooks
 * 3. Click "New Webhook"
 * 4. Copy the Webhook URL to your .env file
 * 
 * That's literally it. No app registration, no OAuth, nothing.
 */

require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const DISCORD_WEBHOOK_URL = process.env.DISCORD_WEBHOOK_URL;

async function postToDiscord(text, options = {}) {
    if (!DISCORD_WEBHOOK_URL) {
        console.log('⚠️  Discord webhook not configured. Skipping.');
        return { success: false, error: 'Missing webhook URL' };
    }

    try {
        const payload = {
            content: text,
            username: options.username || 'Gematria Bot',
            avatar_url: options.avatarUrl || undefined
        };

        // Optional: Create an embed for nicer formatting
        if (options.embed) {
            payload.embeds = [{
                title: options.embed.title || 'Gematria of the Day',
                description: options.embed.description || text,
                color: options.embed.color || 0x9B59B6, // Purple
                timestamp: new Date().toISOString(),
                footer: {
                    text: 'Generated by Gematria Phrase Poster'
                }
            }];
            payload.content = undefined; // Use embed instead
        }

        const response = await fetch(DISCORD_WEBHOOK_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Webhook failed: ${err}`);
        }

        console.log('✅ Discord: Posted successfully!');
        return { success: true };

    } catch (error) {
        console.error('❌ Discord error:', error.message);
        return { success: false, error: error.message };
    }
}

// Test if run directly
if (require.main === module) {
    const testMessage = `🔢 Test post from Gematria Poster - ${new Date().toLocaleString()}`;
    
    // Test with embed
    postToDiscord(testMessage, {
        embed: {
            title: '🔢 Daily Gematria',
            description: testMessage,
            color: 0x9B59B6
        }
    }).then(console.log);
}

module.exports = { postToDiscord };
