/**
 * discord.js - Post to Discord via Webhook (FREE, easiest setup)
 *
 * SETUP:
 * 1. Open Discord, go to your server
 * 2. Right-click a channel → Edit Channel → Integrations → Webhooks
 * 3. Click "New Webhook"
 * 4. Copy the Webhook URL to your .env file
 *
 * That's literally it. No app registration, no OAuth, nothing.
 *
 * WEBHOOKS:
 * - Weekly (Mondays 9am): posts to weekly channel
 * - Monthly (1st of month): posts to monthly channel
 * - Seasonal (start of seasons): posts to seasonal channel
 * - Yearly (Jan 1st): posts to yearly channel
 */

require('dotenv').config({ path: require('path').join(__dirname, '.env') });

// Webhook URLs for different posting schedules
const WEBHOOKS = {
    daily: 'https://discord.com/api/webhooks/1463784586575347769/vu_n8qaeZvARa5Mv60W6E5GeLTlKm208pPnMw5fg_WTkU0iHDd4jyz-_lqEz1Q89awEn',
    weekly: 'https://discord.com/api/webhooks/1463804919856369706/nvMixEpLX2ypBMrX3QmNX-zwnK9Lw1XSU_XI6-DRtBOopE46LfxIOj3oyEr-e4hje381',
    monthly: 'https://discord.com/api/webhooks/1463805663397412924/5o-u-HxcAbtfY2Nq5vK3cYa9SDP_5ZO6aYZIyVZ-qMB8d95cIXCvI-B6RirKd6rs8YXk',
    seasonal: 'https://discord.com/api/webhooks/1463805962405019784/dqle7TQoLz7pciNDbY8H5rQKZ_0bRRtEMVQqbxV6fWL3RlLx-01oqD32R9LWtE5mfnYF',
    yearly: 'https://discord.com/api/webhooks/1463806108693954631/HvMDWANpY39Cs3phhCKSWXWdgGtXa3H_9w2WK-EyLQv1tIq4qRbwK4_T5lKxEsxzQbz9'
};

/**
 * Format a gematria message with proper line-breaks
 * @param {Object} gematriaData - { phrase, value } or { phrase, definitions }
 * @param {string} banner - The banner/title to display
 * @returns {string} Formatted message
 */
function formatGematriaMessage(gematriaData, banner) {
    const { phrase, value, definitions } = gematriaData;

    let message = `${banner}\n\n`;  // Line-break after banner

    if (phrase) {
        message += `**"${phrase}"**\n\n`;
    }

    if (definitions && Array.isArray(definitions)) {
        // Format definitions in compact two-column layout
        const pairs = [];
        for (let i = 0; i < definitions.length; i += 2) {
            if (i + 1 < definitions.length) {
                pairs.push(`${definitions[i]}  |  ${definitions[i + 1]}`);
            } else {
                pairs.push(definitions[i]);
            }
        }
        message += pairs.join('\n');
        message += '\n\n';  // Line-break after last definition
    } else if (value) {
        message += `= ${value}\n\n`;  // Line-break after definition
    }

    message += '#gematria #numerology';

    return message;
}

const fs = require('fs');
const path = require('path');

/**
 * Post to Discord webhook with optional file attachment
 * @param {string} text - Message text
 * @param {string} webhookUrl - Webhook URL
 * @param {Object} options - Options including embed, username, avatarUrl, filePath
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function postToDiscordWebhook(text, webhookUrl, options = {}) {
    if (!webhookUrl) {
        console.log('⚠️  Discord webhook URL not provided. Skipping.');
        return { success: false, error: 'Missing webhook URL' };
    }

    try {
        const payload = {
            content: text,
            username: options.username || 'Gematria Bot',
            avatar_url: options.avatarUrl || undefined
        };

        // Optional: Create an embed for nicer formatting
        if (options.embed) {
            const embed = {
                author: {
                    name: options.username || 'Gematria Bot'
                },
                title: options.embed.title || 'Gematria of the Day',
                description: options.embed.description || text,
                color: options.embed.color || 0x9B59B6, // Purple
                timestamp: new Date().toISOString(),
                footer: {
                    text: options.embed.footer || 'Generated by Gematria Phrase Poster'
                }
            };

            // If we have a file, reference it in the embed
            if (options.filePath && fs.existsSync(options.filePath)) {
                embed.image = { url: 'attachment://output.gif' };
            }

            payload.embeds = [embed];
            payload.content = undefined; // Use embed instead
        }

        // If we have a file to upload, use multipart/form-data
        if (options.filePath && fs.existsSync(options.filePath)) {
            const { FormData, File } = await import('undici');

            const form = new FormData();
            form.append('payload_json', JSON.stringify(payload));

            const fileBuffer = fs.readFileSync(options.filePath);
            const file = new File([fileBuffer], 'output.gif', { type: 'image/gif' });
            form.append('files[0]', file);

            const response = await fetch(webhookUrl, {
                method: 'POST',
                body: form
            });

            if (!response.ok) {
                const err = await response.text();
                throw new Error(`Webhook failed: ${err}`);
            }
        } else {
            // No file, just JSON
            const response = await fetch(webhookUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const err = await response.text();
                throw new Error(`Webhook failed: ${err}`);
            }
        }

        return { success: true };

    } catch (error) {
        console.error('❌ Discord error:', error.message);
        return { success: false, error: error.message };
    }
}

/**
 * Post to Discord (daily - default)
 */
async function postToDiscord(text, options = {}) {
    const webhookUrl = options.webhookUrl || WEBHOOKS.daily;
    console.log('→ Discord (Daily)...');
    const result = await postToDiscordWebhook(text, webhookUrl, options);
    if (result.success) {
        console.log('✅ Discord (Daily): Posted successfully!');
    }
    return result;
}

/**
 * Post to Discord Daily channel (formatted like other channels)
 */
async function postToDiscordDaily(gematriaData, options = {}) {
    const banner = '🔢 Daily Gematria';
    const text = formatGematriaMessage(gematriaData, banner);

    console.log('→ Discord (Daily)...');
    const result = await postToDiscordWebhook(text, WEBHOOKS.daily, {
        ...options,
        embed: {
            title: banner,
            description: text,
            color: 0x9B59B6, // Purple
            footer: 'Daily Gematria'
        }
    });
    if (result.success) {
        console.log('✅ Discord (Daily): Posted successfully!');
    }
    return result;
}

/**
 * Post to Discord Weekly channel (Mondays at 9am)
 */
async function postToDiscordWeekly(gematriaData, options = {}) {
    const banner = '🔢 Weekly Gematria';
    const text = formatGematriaMessage(gematriaData, banner);

    console.log('→ Discord (Weekly)...');
    const result = await postToDiscordWebhook(text, WEBHOOKS.weekly, {
        ...options,
        embed: {
            title: banner,
            description: text,
            color: 0x3498DB, // Blue
            footer: 'Weekly Gematria - Every Monday'
        }
    });
    if (result.success) {
        console.log('✅ Discord (Weekly): Posted successfully!');
    }
    return result;
}

/**
 * Post to Discord Monthly channel (1st of every month)
 */
async function postToDiscordMonthly(gematriaData, options = {}) {
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                        'July', 'August', 'September', 'October', 'November', 'December'];
    const currentMonth = monthNames[new Date().getMonth()];
    const banner = `🔢 ${currentMonth} Gematria`;
    const text = formatGematriaMessage(gematriaData, banner);

    console.log('→ Discord (Monthly)...');
    const result = await postToDiscordWebhook(text, WEBHOOKS.monthly, {
        ...options,
        embed: {
            title: banner,
            description: text,
            color: 0x2ECC71, // Green
            footer: 'Monthly Gematria - 1st of Every Month'
        }
    });
    if (result.success) {
        console.log('✅ Discord (Monthly): Posted successfully!');
    }
    return result;
}

/**
 * Get current season
 */
function getCurrentSeason() {
    const now = new Date();
    const month = now.getMonth();
    const day = now.getDate();

    // Approximate season start dates
    if ((month === 2 && day >= 20) || month === 3 || month === 4 || (month === 5 && day < 21)) {
        return 'Spring';
    } else if ((month === 5 && day >= 21) || month === 6 || month === 7 || (month === 8 && day < 22)) {
        return 'Summer';
    } else if ((month === 8 && day >= 22) || month === 9 || month === 10 || (month === 11 && day < 21)) {
        return 'Autumn';
    } else {
        return 'Winter';
    }
}

/**
 * Post to Discord Seasonal channel (start of each season)
 */
async function postToDiscordSeasonal(gematriaData, options = {}) {
    const season = getCurrentSeason();
    const seasonEmojis = {
        'Spring': '🌸',
        'Summer': '☀️',
        'Autumn': '🍂',
        'Winter': '❄️'
    };
    const seasonColors = {
        'Spring': 0xFF69B4, // Pink
        'Summer': 0xFFD700, // Gold
        'Autumn': 0xFF8C00, // Dark Orange
        'Winter': 0x87CEEB  // Sky Blue
    };

    const banner = `${seasonEmojis[season]} ${season} Gematria`;
    const text = formatGematriaMessage(gematriaData, banner);

    console.log('→ Discord (Seasonal)...');
    const result = await postToDiscordWebhook(text, WEBHOOKS.seasonal, {
        ...options,
        embed: {
            title: banner,
            description: text,
            color: seasonColors[season],
            footer: `Seasonal Gematria - ${season} Edition`
        }
    });
    if (result.success) {
        console.log('✅ Discord (Seasonal): Posted successfully!');
    }
    return result;
}

/**
 * Post to Discord Yearly channel (January 1st)
 */
async function postToDiscordYearly(gematriaData, options = {}) {
    const year = new Date().getFullYear();
    const banner = `🎆 ${year} Gematria`;
    const text = formatGematriaMessage(gematriaData, banner);

    console.log('→ Discord (Yearly)...');
    const result = await postToDiscordWebhook(text, WEBHOOKS.yearly, {
        ...options,
        embed: {
            title: banner,
            description: text,
            color: 0xE74C3C, // Red
            footer: `Yearly Gematria - ${year}`
        }
    });
    if (result.success) {
        console.log('✅ Discord (Yearly): Posted successfully!');
    }
    return result;
}

// Test if run directly
if (require.main === module) {
    const testData = {
        phrase: 'Test phrase',
        value: '1111/666/111/99',
        definitions: [
            'English: 1111',
            'Hebrew: 666',
            'Simple: 111',
            'Reduced: 99'
        ]
    };

    const testMessage = formatGematriaMessage(testData, '🔢 Test Gematria');
    console.log('Formatted message preview:');
    console.log('---');
    console.log(testMessage);
    console.log('---');

    // Test weekly posting
    postToDiscordWeekly(testData).then(console.log);
}

module.exports = {
    postToDiscord,
    postToDiscordDaily,
    postToDiscordWeekly,
    postToDiscordMonthly,
    postToDiscordSeasonal,
    postToDiscordYearly,
    postToDiscordWebhook,
    formatGematriaMessage,
    WEBHOOKS
};
